
blueprint:
  name: Taktgeber für input_booleans
  description: |
    Dieser Blueprint schaltet konfigurierbare input_booleans in festen Intervallen an und aus (Toggle).
    Ideal zur Verwendung als Trigger-Ersatz für time_pattern.
  domain: automation
  input:
    toggles:
      name: Zeitgeber-Konfiguration
      description: Liste von input_booleans mit Intervall in Minuten
      default: []
      selector:
        object: {}

mode: single

variables:
  toggle_config: !input toggles

trigger:
  - platform: time_pattern
    minutes: "/1"

action:
  - repeat:
      for_each: "{{ toggle_config }}"
      sequence:
        - variables:
            entity: "{{ repeat.item.entity_id }}"
            interval: "{{ repeat.item.interval }}"
            last_trigger: "{{ state_attr(entity, 'last_triggered') }}"
        - condition: template
          value_template: >
            {% set last = as_timestamp(last_trigger) if last_trigger else 0 %}
            {% set now = as_timestamp(now()) %}
            {{ (now - last) >= (interval * 60) }}
        - service: input_boolean.toggle
          target:
            entity_id: "{{ entity }}"
